# Generated by Django 5.2.13 on 2026-04-13 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama kategori aset (contoh: Elektronik, Furniture)', max_length=100, unique=True, verbose_name='Nama Kategori')),
                ('description', models.TextField(blank=True, help_text='Deskripsi kategori aset', null=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Kode unik ruangan (contoh: A301, Lab-Komputer-1)', max_length=50, unique=True, verbose_name='Kode Ruangan')),
                ('name', models.CharField(help_text='Nama lengkap ruangan', max_length=200, verbose_name='Nama Ruangan')),
                ('building', models.CharField(help_text='Nama gedung (contoh: Gedung A, Gedung B)', max_length=100, verbose_name='Gedung')),
                ('floor', models.IntegerField(blank=True, help_text='Nomor lantai', null=True, verbose_name='Lantai')),
                ('capacity', models.IntegerField(blank=True, help_text='Kapasitas ruangan (jumlah orang)', null=True, verbose_name='Kapasitas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
            ],
            options={
                'verbose_name': 'Ruangan',
                'verbose_name_plural': 'Ruangan',
                'db_table': 'rooms',
                'ordering': ['building', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Kode unik aset (format: AST-YYYY-NNN)', max_length=50, unique=True, verbose_name='Kode Aset')),
                ('name', models.CharField(help_text='Nama aset', max_length=200, verbose_name='Nama Aset')),
                ('description', models.TextField(blank=True, help_text='Deskripsi detail aset', null=True, verbose_name='Deskripsi')),
                ('is_space', models.BooleanField(default=False, help_text='True jika aset adalah ruangan, False jika barang', verbose_name='Adalah Ruangan')),
                ('status', models.CharField(choices=[('TERSEDIA', 'Tersedia'), ('DIPINJAM', 'Sedang Dipinjam'), ('PERBAIKAN', 'Dalam Perbaikan'), ('RUSAK', 'Rusak')], default='TERSEDIA', help_text='Status ketersediaan aset', max_length=20, verbose_name='Status')),
                ('purchase_date', models.DateField(blank=True, help_text='Tanggal pembelian aset', null=True, verbose_name='Tanggal Pembelian')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Harga pembelian aset (Rupiah)', max_digits=15, null=True, verbose_name='Harga Pembelian')),
                ('condition_notes', models.TextField(blank=True, help_text='Catatan kondisi aset', null=True, verbose_name='Catatan Kondisi')),
                ('qr_code', models.CharField(blank=True, help_text='Path ke file QR code image', max_length=255, null=True, verbose_name='QR Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tanggal Diupdate')),
                ('category', models.ForeignKey(help_text='Kategori aset', on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='inventory.category', verbose_name='Kategori')),
                ('room', models.ForeignKey(blank=True, help_text='Lokasi/ruangan tempat aset berada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='inventory.room', verbose_name='Lokasi')),
            ],
            options={
                'verbose_name': 'Aset',
                'verbose_name_plural': 'Aset',
                'db_table': 'assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_code', models.CharField(help_text='Kode unik peminjaman (format: PJM-YYYY-NNN)', max_length=50, unique=True, verbose_name='Kode Peminjaman')),
                ('borrower_type', models.CharField(choices=[('GUEST', 'Guest (Mahasiswa dengan NIM)'), ('UKM', 'UKM Account')], help_text='Tipe peminjam: Guest (NIM) atau UKM Account', max_length=20, verbose_name='Tipe Peminjam')),
                ('guest_nim', models.CharField(blank=True, help_text='NIM mahasiswa (untuk borrower_type GUEST)', max_length=20, null=True, verbose_name='NIM Mahasiswa')),
                ('guest_name', models.CharField(blank=True, help_text='Nama mahasiswa (untuk borrower_type GUEST)', max_length=200, null=True, verbose_name='Nama Mahasiswa')),
                ('guest_phone', models.CharField(blank=True, help_text='Nomor telepon mahasiswa (untuk borrower_type GUEST)', max_length=20, null=True, verbose_name='Nomor Telepon Mahasiswa')),
                ('loan_date', models.DateField(help_text='Tanggal mulai peminjaman', verbose_name='Tanggal Pinjam')),
                ('return_date', models.DateField(help_text='Tanggal rencana pengembalian', verbose_name='Tanggal Kembali')),
                ('purpose', models.TextField(help_text='Keperluan/tujuan peminjaman', verbose_name='Keperluan')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Persetujuan'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('RETURNED', 'Sudah Dikembalikan')], default='PENDING', help_text='Status peminjaman', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tanggal Diupdate')),
                ('ukm_account', models.ForeignKey(blank=True, help_text='Akun UKM yang meminjam (untuk borrower_type UKM)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_requests', to=settings.AUTH_USER_MODEL, verbose_name='Akun UKM')),
            ],
            options={
                'verbose_name': 'Peminjaman',
                'verbose_name_plural': 'Peminjaman',
                'db_table': 'loan_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Jumlah aset yang dipinjam', verbose_name='Jumlah')),
                ('notes', models.TextField(blank=True, help_text='Catatan tambahan untuk item ini', null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('asset', models.ForeignKey(help_text='Aset yang dipinjam', on_delete=django.db.models.deletion.PROTECT, related_name='loan_items', to='inventory.asset', verbose_name='Aset')),
                ('loan_request', models.ForeignKey(help_text='Peminjaman terkait', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.loanrequest', verbose_name='Peminjaman')),
            ],
            options={
                'verbose_name': 'Item Peminjaman',
                'verbose_name_plural': 'Item Peminjaman',
                'db_table': 'loan_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMITTED', 'Diajukan'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak')], help_text='Aksi yang dilakukan', max_length=20, verbose_name='Aksi')),
                ('notes', models.TextField(blank=True, help_text='Catatan/alasan approval atau rejection', null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal')),
                ('approver', models.ForeignKey(blank=True, help_text='Staff yang approve/reject (NULL untuk SUBMITTED)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_logs', to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
                ('loan_request', models.ForeignKey(help_text='Peminjaman terkait', on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='inventory.loanrequest', verbose_name='Peminjaman')),
            ],
            options={
                'verbose_name': 'Log Approval',
                'verbose_name_plural': 'Log Approval',
                'db_table': 'approval_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['loan_code'], name='loan_reques_loan_co_c506dc_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['status'], name='loan_reques_status_9bc4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['borrower_type', 'status'], name='loan_reques_borrowe_26e38c_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['guest_nim'], name='loan_reques_guest_n_b0f8f2_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['code'], name='assets_code_5f20be_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_status_326766_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category', 'status'], name='assets_categor_c87708_idx'),
        ),
    ]
